#ifndef ERROR_CODES_H
#define ERROR_CODES_H
#include <string>

typedef int64_t   CODE_UID;
enum ERROR_CODES_BACCT {
    ERROR_OK=0,
    ERROR_OTHER=-1,
    ERROR_MIN_OPTS=-2,
    ERROR_BET_FAILED=-3,
    ERROR_OPT_NOT_FOUND=-4,
    ERROR_SCHEME_NOT_FOUND=-5,
    ERROR_NOT_ENOUGH_POINTS=-6,
    ERROR_QUERY_FAILED=-7,
    ERROR_USER_NOT_FOUND=-8,
    ERROR_USER_POINTS_NULL=-9,
    ERROR_SCHEME_CREATION_FAILED=-10,
    ERROR_MIN_OPTS_FOR_SCHEME=-11,
    ERROR_USER_CREATION_FAILED=-12,
    ERROR_FINALIZE_FAILED=-13,
    ERROR_UNDEFINED=-9999
};

extern const char **ERROR_NAMES_BACCT;
const char* map_error(ERROR_CODES_BACCT err);

#endif // ERROR_CODES_H
